yatube/about/urls.py
from django.urls import path

from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path(
        'posts/<int:post_id>/comment/',
        views.add_comment,
        name='add_comment'
    ),
    path('follow/', views.follow_index, name='follow_index'),

    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),

]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('', include('posts.urls', namespace='posts')),
    path('about/', include('about.urls', namespace='about')),
]

handler404 = "core.views.page_not_found"
handler403 = "core.views.permission_denied"
handler500 = "core.views.server_error"

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Group(models.Model):
    title = models.CharField(
        'Название групп',
        max_length=200,
    )
    slug = models.SlugField(
        'Хэштег',
        unique=True
    )
    description = models.TextField(
        'Описание',
        max_length=400
    )

    class Meta:
        verbose_name_plural = 'Группы'

    def __str__(self) -> str:
        return self.title


class Post(models.Model):
    text = models.TextField('Текст')
    pub_date = models.DateTimeField(
        'Дата публикации',
        auto_now_add=True,
        db_index=True
    )
    author = models.ForeignKey(
        User,
        verbose_name='Автор',
        on_delete=models.CASCADE,
        related_name='posts'
    )
    group = models.ForeignKey(
        Group,
        verbose_name='Группа',
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='posts'
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )

    class Meta:
        ordering = ('-pub_date',)
        verbose_name_plural = 'Посты'

    def __str__(self) -> str:
        return self.text[:15]


class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        verbose_name="Пост",
        related_name="comments",
        on_delete=models.CASCADE,
    )
    author = models.ForeignKey(
        User,
        verbose_name="Автор",
        related_name="comments",
        on_delete=models.CASCADE,
    )
    text = models.TextField(
        verbose_name="Текст",
        help_text="Напишите комментарий"
    )
    created = models.DateTimeField(
        verbose_name="Дата публикации",
        auto_now_add=True,
    )

    class Meta:
        ordering = ["-created"]
        verbose_name_plural = 'Комментарии'

    def __str__(self):
        return self.text[:30]


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower',
        help_text='Пользователь, который подписывается',
        verbose_name='Подписчик',
    )

    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following',
        help_text='На кого подписываются',
        verbose_name='Автор',
    )

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=['user', 'author'], name='unique_follow')
        ]

    def __str__(self):
        return f'Пользователь {self.user} подписался на {self.author}'

yatube/posts/forms.py
from django.forms import ModelForm

from .models import Comment, Post


class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = ("text", "group", "image")
        labels = {
            "text": "Текст",
            "group": "Группа",
        }
        help_texts = {
            "text": "Введите текст",
            "group": "Выберите группу",
        }


class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ("text",)
        labels = {
            "text": "Текст",
        }
        help_texts = {
            "text": "Не стесняйся, озвучь свое мнение",
        }

yatube/posts/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect, render

from .models import Follow, Group, Post, User
from .forms import CommentForm, PostForm
from .utils import get_page_context


def index(request):
    page_obj = get_page_context(
        request, Post.objects.select_related('author', 'group').all()
    )
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    page_obj = get_page_context(
        request, group.posts.select_related('author').all()
    )
    context = {
        'group': group,
        'page_obj': page_obj,
    }
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    author = get_object_or_404(User, username=username)
    posts = author.posts.select_related('group').all()
    posts_count_author = posts.count()
    page_obj = get_page_context(request, posts)
    following = (request.user.is_authenticated
                 and request.user != author
                 and author.following.
                 filter(user=request.user).exists())
    context = {
        'author': author,
        'posts_count_author': posts_count_author,
        'page_obj': page_obj,
        'following': following,
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    post = get_object_or_404(
        Post.objects.select_related('author').
        prefetch_related('comments__author'),
        pk=post_id
    )
    comment_form = CommentForm(request.POST or None)
    context = {
        'post': post,
        'form': comment_form,
        'comments': post.comments.all(),
    }

    return render(request, 'posts/post_detail.html', context)


@login_required(login_url='/auth/login/')
def post_create(request):
    user = request.user

    form = PostForm(
        request.POST or None,
        files=request.FILES or None
    )
    if form.is_valid():
        post = form.save(False)
        post.author = user
        post.save()
        return redirect('posts:profile', user.username)

    return render(request, 'posts/create_post.html', {'form': form})


@login_required(login_url='/auth/login/')
def post_edit(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if post.author != request.user:
        return redirect('posts:post_detail', post_id=post_id)

    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post
    )
    if form.is_valid():
        form.save()
        return redirect('posts:post_edit', post_id=post_id)
    context = {
        'post': post,
        'form': form,
        'is_edit': True,
    }
    return render(request, 'posts/create_post.html', context)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    posts_list = (Post.objects.select_related('author', 'group').
                  filter(author__following__user=request.user))
    page_obj = get_page_context(request, posts_list)
    context = {'page_obj': page_obj,
               'follow': True, }
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    auhtor = get_object_or_404(User, username=username)
    user = request.user
    if auhtor != user:
        Follow.objects.get_or_create(user=user, author=auhtor)
    return redirect('posts:profile', username)


@login_required
def profile_unfollow(request, username):
    unfollow_from_author = get_object_or_404(User, username=username)
    Follow.objects.filter(user=request.user).filter(
        author=unfollow_from_author
    ).delete()
    return redirect('posts:profile', username)

yatube/templates/posts/create_post.html
{% extends "base.html" %}

{% load thumbnail %}

{% block title %}{% if form.instance.pk %} Редактировать запись {% else %} Добавить запись {% endif %}{% endblock %}

{% block content %}
{% load user_filters%}
  <div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">

          <div class="card-header">{% if form.instance.pk %} Редактировать запись {% else %} Добавить запись {% endif %}</div>

          <div class="card-body">
            {% include 'includes/error_form.html' %}

            <form method="post" enctype="multipart/form-data" action={% if form.instance.pk %}"{% url 'posts:post_edit' form.instance.pk %}"{% else %}"{% url 'posts:post_create' %}"{% endif %}>

              {% csrf_token %}      
              {% include 'includes/for_form.html' %}

              <div class="col-md-6 offset-md-4">              
                <button type="submit" class="btn btn-primary">
                  {% if form.instance.pk %} Сохранить {% else %} Добавить {% endif %}
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

yatube/templates/posts/follow.html
{% extends 'base.html' %} 

{% load cache %}

{% block title %}
   Подписки
{% endblock %}

{% block content %}

  <div class="container py-5">     
      <h1>Последниe обновления на сайте</h1>
      
      {% include 'posts/includes/switcher.html' with follow=True %}

      {% cache 30 follow_index page_obj.number %}
      {% for post in page_obj %}
        {% include 'posts/includes/article.html' %}
        {% if not forloop.last %}<hr>{% endif %}
      {% endfor %}
      {% include 'posts/includes/paginator.html' %}
      {% endcache %} 
  </div>  
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}

{% block title %}
   Записи группы - {{ group.title }}
{% endblock %}

{% block content %}
  <div class="container py-5">
      <h1>{{ group.title }}</h1>
      <p>{{ group.description|linebreaksbr }}</p>
      
      {% for post in page_obj %}
        {% include 'posts/includes/article.html' with check_group=True %}
        {% if not forloop.last %}<hr>{% endif %}
      {% endfor %} 
      {% include 'posts/includes/paginator.html' %}
  </div>  
{% endblock %} 

yatube/templates/posts/index.html
{% extends 'base.html' %}

{% load cache %}

{% block title %}
   Это главная страница проекта Yatube
{% endblock %}

{% block content %}

  <div class="container py-5">     
      <h1>Последниe обновления на сайте</h1>

      {% include 'posts/includes/switcher.html' with index=True %}
      {% cache 30 index page_obj.number %}
      {% for post in page_obj %}
        {% include 'posts/includes/article.html' %}
        {% if not forloop.last %}<hr>{% endif %}
      {% endfor %}
      {% include 'posts/includes/paginator.html' %}
      {% endcache %} 
  </div>  
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}

{#{% load thumbnail %}#}

{% block title %}
    Пост {{ post.text|slice:30 }}
{% endblock %}

{% block content %}
  <div class="row">
      <aside class="col-12 col-md-3">
        <ul class="list-group list-group-flush">
          <li class="list-group-item">
              Дата публикации: {{ post.pub_date|date:"d E Y" }}
          </li>
          {% if post.group %}
            <li class="list-group-item">
              Группа: {{ group.title }}
              <a href="{% url 'posts:group_list' post.group.slug %}">#{{post.group}}</a>
            </li>
          {% else %}
            <span style='color: red'>Этой публикации нет ни в одном сообществе.</span>
          {% endif %}

          <li class="list-group-item">
            Автор: {{ post.author.get_full_name }}
          </li>
          <li class="list-group-item d-flex justify-content-between align-items-center">
            Всего постов автора:  <span >{{ post.author.posts.count }}</span>
          </li>
          <li class="list-group-item">
            <a href="{% url 'posts:profile' post.author.username %}">
              Все посты пользователя
            </a>
          </li>
        </ul>
      </aside>
      <article class="card">

        {#{% thumbnail item.image "900x400" crop="center" as im %}#}

        {#<img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}">#}
        {#{% endthumbnail %}#}
  
        <p>{{ post.text|linebreaksbr }}</p>

        {% if user.is_authenticated %}
          {% include 'posts/includes/comment_create.html' %}
        {% endif %}
          {% include 'posts/includes/comments_display.html' %}
          
        {% if post.author == user %}
          <a href="{% url 'posts:post_edit' post.id %}">Редактировать запись</a>
        {% endif %}
      </article>
  </div> 
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}

{% block title %}
   Профайл пользователя {{ author.get_full_name }}
{% endblock %}

{% block content %}
  <div class="container py-5">        
      <h1>Все посты пользователя {{ author }} </h1>
      <h3>Всего постов: {{ posts_count_author }} </h3>
      <h3>Подписки: {{ author.follower.count }} </h3> 
      <h3>Подписчики: {{ author.following.count }} </h3> 
      <div class="mb-5">

      {% if request.user.is_authenticated and user != author %}
        {% if following %}
          <a
            class="btn btn-lg btn-light"
            href="{% url 'posts:profile_unfollow' author.username %}" role="button"
          >
            Отписаться
          </a>
        {% else %}
            <a
              class="btn btn-lg btn-primary"
              href="{% url 'posts:profile_follow' author.username %}" role="button"
            >
              Подписаться
            </a>
        {% endif %}
      {% endif %}
    </div>
         

      {% for post in page_obj %}
        {% include 'posts/includes/article.html' with check_author=True %}
        {% if not forloop.last %}<hr>{% endif %}
      {% endfor %}
      {% include 'posts/includes/paginator.html' %}
  </div>
{% endblock %}